version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: circlepass_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./terraform/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: omoluabi44/circlepass-frontend:latest
    container_name: circlepass_frontend
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=uD9x#K7^mP2!qR5vT8*bN4@fW1$yH6&c
      - NEXTAUTH_URL=https://thecirclepass.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: omoluabi44/circlepass-backend:latest
    container_name: circlepass_backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: circlepass_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

