"""
Secure QR token generation for CirclePass digital tickets.

Generates HMAC-signed tokens using a dedicated TICKET_QR_SECRET.
QR codes contain only the secure token — never raw database IDs or sensitive data.
"""
import hashlib
import hmac
import os
import uuid

from django.conf import settings


def _get_qr_secret() -> bytes:
    """
    Return the signing secret for QR tokens.
    Uses TICKET_QR_SECRET env var; falls back to Django SECRET_KEY (dev only).
    """
    secret = os.environ.get('TICKET_QR_SECRET', '')
    if not secret:
        secret = settings.SECRET_KEY
    return secret.encode('utf-8')


def generate_secure_qr_token() -> str:
    """
    Generate a secure, unguessable QR token for a ticket.

    Format: ``<uuid4>.<hmac_signature>``

    The UUID provides uniqueness, and the HMAC signature prevents forgery.
    """
    token_id = uuid.uuid4().hex  # 32-char hex string
    signature = hmac.new(
        _get_qr_secret(),
        msg=token_id.encode('utf-8'),
        digestmod=hashlib.sha256,
    ).hexdigest()[:16]  # Truncate to 16 chars for a compact code
    return f'{token_id}.{signature}'


def verify_qr_token(token: str) -> bool:
    """
    Verify that a QR token was generated by this system (i.e. the HMAC is valid).

    Returns True if the signature matches; False otherwise.
    This does NOT check database validity — only cryptographic integrity.
    """
    if '.' not in token:
        return False

    token_id, provided_sig = token.rsplit('.', 1)
    expected_sig = hmac.new(
        _get_qr_secret(),
        msg=token_id.encode('utf-8'),
        digestmod=hashlib.sha256,
    ).hexdigest()[:16]
    return hmac.compare_digest(provided_sig, expected_sig)
