"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

export function HowItWorks() {
  const [activeTab, setActiveTab] = useState(0);
  const [openAccordion, setOpenAccordion] = useState<number | null>(0);

  const tabs = [
    {
      title: "Create & Publish",
      items: [
        { title: "Event Creation", desc: "Bring your event to life from one place. Add your event name, description, date, venue and other essential details, then build everything you need before publishing." },
        { title: "Free & Paid Events", desc: "Whether you're hosting a free gathering or selling tickets, CirclePass gives you the flexibility to create the event that fits your audience." },
        { title: "Multiple Ticket Types", desc: "Create different ticket categories for your event, each with its own pricing, availability and quantity. Give attendees options that suit their needs while keeping your ticket structure organized." },
        { title: "Ticket Pricing & Availability", desc: "Set your ticket prices and control how many tickets are available. Manage your inventory as sales progress so you always know what is still available." },
        { title: "Event Details & Customisation", desc: "Give attendees the information they need to make a decision. Add your event description, venue, date, time and other details to create a clear and informative event page." },
        { title: "Draft & Submission", desc: "Not ready to publish? Save your event as a draft and return to it whenever you're ready. Once complete, submit it through the CirclePass review process." },
        { title: "Review & Publishing", desc: "CirclePass gives organizers a structured path from creating an event to making it public. Once an event has completed the required review, it can be published for attendees to discover." },
        { title: "Attendee Information", desc: "Collect the relevant information you need from attendees during checkout, helping you better understand and manage the people coming to your event." },
      ]
    },
    {
      title: "Sell & Connect",
      items: [
        { title: "Event Discovery", desc: "Put your event where people are already looking for experiences. Attendees can discover events on CirclePass and find opportunities that match their interests." },
        { title: "Online Ticket Sales", desc: "Turn interest into attendance with a straightforward ticket purchase experience. Attendees can select their ticket, complete payment and receive their digital pass." },
        { title: "Secure Payments", desc: "CirclePass uses Paystack to process ticket payments, supporting card, bank transfer and USSD payment options for a convenient checkout experience." },
        { title: "Service Fee Flexibility", desc: "Organizers can choose how the CirclePass service fee is handled—either absorbing the fee or allowing it to be covered by the ticket buyer." },
        { title: "Digital Tickets", desc: "Once a ticket is purchased, attendees receive a digital pass they can access for their event. No physical ticket is needed to keep their admission details close at hand." },
        { title: "Digital Ticket Wallet", desc: "Keep CirclePass tickets together in one convenient place. Attendees can access their passes when they need them, making the journey from purchase to entry simpler." },
        { title: "Automated Emails", desc: "Keep communication moving without having to handle every message manually. CirclePass can send relevant automated emails to organizers and attendees throughout the event journey." },
        { title: "Announcements", desc: "Keep your audience informed when something changes or an important update needs to be shared. Organizers can communicate key information directly around their event." },
        { title: "Smart Waitlist", desc: "Don't lose interested attendees when tickets become unavailable. CirclePass lets people join a waitlist, helping organizers capture demand while keeping potential attendees connected." },
      ]
    },
    {
      title: "Manage & Analyse",
      items: [
        { title: "Event Dashboard", desc: "Manage the important parts of your event from one central place. Get a clear view of your event activity without having to work across multiple systems." },
        { title: "Attendee Management", desc: "Keep track of the people attending your event. Access attendee information and stay organized as ticket sales grow." },
        { title: "Sales Tracking", desc: "Monitor ticket sales as they happen. See how your tickets are moving and stay informed about the progress of your event." },
        { title: "Revenue Tracking", desc: "Keep an eye on the financial side of your ticket sales. Understand the revenue generated by your event and track performance as sales progress." },
        { title: "Event Analytics", desc: "Go beyond simply counting tickets. CirclePass provides insights into sales, revenue and attendee activity, helping organizers understand performance and make better decisions." },
        { title: "Ticket Inventory", desc: "Stay in control of your available tickets. Monitor quantities across your ticket types and keep track of what remains as people purchase." },
        { title: "Event Communication", desc: "Keep your attendees informed throughout the event journey with announcements and automated communication, helping important information reach the right people." },
      ]
    },
    {
      title: "Check In & Engage",
      items: [
        { title: "QR Code Check-In", desc: "Make entry faster and easier with QR-powered ticket verification. Organizers can scan attendee tickets at the entrance and quickly confirm whether they are valid." },
        { title: "Attendance Tracking", desc: "Know who has arrived at your event. Check-in activity gives organizers a clearer picture of attendance as guests enter." },
        { title: "QR Activation Controls", desc: "Keep ticket access aligned with your event timing. QR tickets can be controlled so they become active around the appropriate point before the event begins." },
        { title: "Seamless Entry", desc: "Reduce the stress that often comes with event admission. With digital tickets and QR verification, attendees can move from their ticket to the entrance with fewer complications." },
      ]
    },
    {
      title: "Beyond Ticketing",
      items: [
        { title: "Voting", desc: "CirclePass isn't limited to ticketed events. Create standalone voting campaigns for elections, awards, competitions and other experiences that require structured voting." },
        { title: "Nominations", desc: "Give participants a clear way to submit nominees before voting begins. Build a nomination stage into your campaign and collect potential candidates in one place." },
        { title: "Nominee Review & Approval", desc: "Review nominations before opening the ballot. Organizers can assess submissions and approve eligible nominees for the voting stage." },
        { title: "Voting", desc: "Launch the voting stage when you're ready and allow participants to cast their votes through a structured digital voting experience." },
        { title: "Results", desc: "Monitor voting activity and see how your campaign is progressing. Results give organizers a clearer view of the outcome as votes come in." },
        { title: "Campaign Management", desc: "Manage the campaign from its beginning to its conclusion. Once voting is complete, close and archive the campaign while keeping its outcome organized." },
      ]
    }
  ];

  return (
    <section className="py-24 px-4 bg-background" id="how-it-works">
      <div className="container mx-auto max-w-5xl">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-extrabold text-foreground tracking-tight mb-4">
            How CirclePass Works
          </h2>
          <p className="text-lg text-muted-foreground font-medium max-w-2xl mx-auto">
            Everything you need to create, sell, manage and deliver better event experiences, all in one place.
          </p>
        </div>

        {/* Desktop Tabs */}
        <div className="hidden md:flex flex-wrap justify-center gap-2 mb-12">
          {tabs.map((tab, idx) => (
            <button
              key={idx}
              onClick={() => {
                setActiveTab(idx);
                setOpenAccordion(0); // Reset accordion when switching tabs
              }}
              className={`px-6 py-3 rounded-full text-[15px] font-bold transition-all duration-300 ${
                activeTab === idx
                  ? "bg-primary text-primary-foreground shadow-md scale-105"
                  : "bg-secondary/50 text-muted-foreground hover:bg-secondary hover:text-foreground"
              }`}
            >
              {tab.title}
            </button>
          ))}
        </div>

        {/* Mobile Tabs Dropdown or Scrollable flex */}
        <div className="md:hidden flex overflow-x-auto pb-4 mb-8 snap-x snap-mandatory hide-scrollbar gap-3">
          {tabs.map((tab, idx) => (
            <button
              key={idx}
              onClick={() => {
                setActiveTab(idx);
                setOpenAccordion(0);
              }}
              className={`px-5 py-2.5 rounded-full text-sm font-bold whitespace-nowrap snap-start transition-all ${
                activeTab === idx
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "bg-secondary text-muted-foreground"
              }`}
            >
              {tab.title}
            </button>
          ))}
        </div>

        {/* Accordion Content */}
        <div className="bg-secondary/20 rounded-3xl p-6 md:p-10 border border-border/50 shadow-sm max-w-4xl mx-auto min-h-[400px]">
          <h3 className="text-2xl font-extrabold text-foreground mb-8 pb-4 border-b border-border/50">
            {tabs[activeTab].title}
          </h3>
          <div className="space-y-4">
            {tabs[activeTab].items.map((item, idx) => {
              const isOpen = openAccordion === idx;
              return (
                <div key={idx} className={`border border-border/50 rounded-2xl overflow-hidden transition-all duration-300 ${isOpen ? 'bg-card shadow-sm ring-1 ring-primary/20' : 'bg-transparent hover:bg-card/50'}`}>
                  <button
                    onClick={() => setOpenAccordion(isOpen ? null : idx)}
                    className="w-full text-left px-6 py-4 flex items-center justify-between focus:outline-none"
                  >
                    <span className={`font-bold text-base md:text-lg transition-colors ${isOpen ? 'text-primary' : 'text-foreground'}`}>
                      {item.title}
                    </span>
                    <ChevronDown className={`w-5 h-5 transition-transform duration-300 shrink-0 ml-4 ${isOpen ? 'rotate-180 text-primary' : 'text-muted-foreground'}`} />
                  </button>
                  <div 
                    className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${isOpen ? 'max-h-40 pb-5 opacity-100' : 'max-h-0 opacity-0'}`}
                  >
                    <p className="text-muted-foreground leading-relaxed text-[15px] max-w-3xl">
                      {item.desc}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
