import Cookies from 'js-cookie';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

/**
 * Uploads a file directly to an AWS S3 bucket via a presigned URL generated by the backend.
 * Uses the AWS CloudFront CDN URL for the return if configured in the backend.
 * 
 * @param file The file object from an input element to be uploaded
 * @param folder The target folder prefix in S3 (e.g., 'event_covers', 'organizer_logos')
 * @param token Optional JWT Bearer token from session (bypasses cookie lookup if provided)
 * @returns A promise that resolves to the final public URL of the uploaded image.
 */
export async function uploadToS3(file: File, folder: string = 'uploads', token?: string): Promise<string> {
  const authToken = token || Cookies.get('accessToken');
  if (!authToken) {
    throw new Error('Authentication required for uploading.');
  }

  // 1. Get Presigned URL from Backend
  const response = await fetch(`${API_URL}/upload/presigned-url/`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${authToken}`
    },
    body: JSON.stringify({
      filename: file.name,
      file_type: file.type,
      folder: folder
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error || 'Failed to get presigned URL from backend');
  }

  const data = await response.json();
  const uploadUrl = data.upload_url;
  const fileUrl = data.file_url;

  // 2. Upload file directly to S3 via Presigned URL
  const uploadResponse = await fetch(uploadUrl, {
    method: 'PUT',
    headers: {
      'Content-Type': file.type
    },
    body: file
  });

  if (!uploadResponse.ok) {
    throw new Error('Failed to upload file directly to S3');
  }

  // 3. Return the final public CDN/S3 URL
  return fileUrl;
}
