# Generated by Django 5.0.14 on 2026-09-15 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_capacity_event_description_event_is_online_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='event',
            name='absorb_fees',
            field=models.BooleanField(default=False, help_text='If True, organizer absorbs the 5% CirclePass fee. If False, buyer pays it.'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, help_text='Discount amount in kobo.'),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_amount',
            field=models.IntegerField(default=0, help_text='CirclePass 5% service fee in kobo. 0 if free or absorbed.'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='For guest checkout when attendee is null.', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0, help_text='Sum of ticket prices in kobo, before fees/discounts.'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee_name',
            field=models.CharField(blank=True, help_text='Name on ticket (supports buying for others).', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.IntegerField(default=0, help_text='Number of tickets sold. Updated atomically.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sale_end',
            field=models.DateTimeField(blank=True, help_text='When this ticket stops selling.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sale_start',
            field=models.DateTimeField(blank=True, help_text='When this ticket goes on sale.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display ordering within the event.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('EARLY_BIRD', 'Early Bird'), ('REGULAR', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP'), ('CUSTOM', 'Custom')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attendeeprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='Final amount charged in kobo: subtotal - discount + fee.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tickettype'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='core.event'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Display name, e.g. "Super Early Bird", "Gold Table"', max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in kobo. Must be 0 for FREE tier.'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total inventory for this ticket type.'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(help_text='Price per ticket in kobo at time of purchase.')),
                ('line_total', models.IntegerField(help_text='unit_price * quantity in kobo.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tickettype')),
            ],
        ),
    ]
