# Generated by Django 5.0.14 on 2026-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_expires_at_payment_channel_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Lucide icon name, e.g., 'Music'", max_length=50),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to background cover image'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
