# Generated by Django 5.0.14 on 2026-09-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.ticket'),
        ),
    ]
