# Generated by Django 5.0.14 on 2026-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newslettersubscriber_discount_discountredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, help_text="e.g., '18+', 'None', '21 and over'", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='dress_code',
            field=models.CharField(blank=True, help_text="e.g., 'Casual', 'Black Tie', 'No specific dress code'", max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact info.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='lineup',
            field=models.TextField(blank=True, help_text='Lineup or artists where applicable'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_contact',
            field=models.CharField(blank=True, help_text='Email or phone for attendee inquiries.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='personalized_dp_enabled',
            field=models.BooleanField(default=False, help_text='Organizer can enable/disable Personalized DP for the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
