# Generated by Django 5.0.14 on 2026-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_age_restriction_event_city_event_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_logos/'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
