# Generated by Django 5.0.14 on 2026-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organizerprofile_bio_organizerprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
