# Generated by Django 5.0.14 on 2026-09-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendeeprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerverification',
            name='cac_document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/cac/'),
        ),
        migrations.AddField(
            model_name='organizerverification',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/id/'),
        ),
        migrations.AddField(
            model_name='organizerverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organizerverification',
            name='status',
            field=models.CharField(default='Unverified', max_length=50),
        ),
    ]
