# Generated by Django 5.0.14 on 2026-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organizerverification_cac_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerwallet',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizerwallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organizerwallet',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
