# Generated by Django 5.0.14 on 2026-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organizerwallet_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sales_paused',
            field=models.BooleanField(default=False, help_text='If True, ticket sales are paused.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=False, help_text='If True, waitlist is enabled for sold out tickets.'),
        ),
    ]
