# Generated by Django 5.0.14 on 2026-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_sales_paused_event_waitlist_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_onsite_services',
            field=models.BooleanField(default=False, help_text='Charges 13% of ticket price if enabled.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
