# Generated by Django 5.0.14 on 2026-09-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_has_onsite_services_alter_event_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Code of the promoter or affiliate', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerwallet',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
