# Generated by Django 5.0.14 on 2026-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='For guest checkout phone number.', max_length=20),
        ),
    ]
