# Generated by Django 5.0.14 on 2026-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of page views'),
        ),
    ]
