# Generated by Django 5.0.14 on 2026-10-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_checkin_scanned_by_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='rejection_reason',
            new_name='failure_reason',
        ),
        migrations.AddField(
            model_name='payout',
            name='amount_received',
            field=models.IntegerField(default=0, help_text='amount - payout_charge: what organizer actually receives (kobo).'),
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_charge',
            field=models.IntegerField(default=0, help_text='Paystack transfer fee in kobo.'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.payout'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.IntegerField(help_text='Total amount deducted from available_balance (kobo).'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PROCESSING', max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.organizerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organizer', 'account_number', 'bank_code')},
            },
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='core.organizerbankaccount'),
        ),
        migrations.CreateModel(
            name='PayoutWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Paystack transfer event key for idempotency.', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='e.g. transfer.success', max_length=100)),
                ('raw_body', models.JSONField(help_text='Full webhook payload.')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='core.payout')),
            ],
        ),
    ]
