# Generated by Django 5.0.14 on 2026-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organizer_bank_accounts_payout_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram handle for the event', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, help_text='Optional name of the location', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tiktok_handle',
            field=models.CharField(blank=True, help_text='TikTok handle for the event', max_length=100),
        ),
    ]
